version: "3.3"

services:
 redis_httpserver: 
  container_name: redis_httpserver
  image: bytehero/redis_httpserver
  depends_on:
   - redis
  links:
   - redis:redis
  ports:
   - "8080:80"

 redis:
  container_name: redis
  image: redis
